# Generated by Django 4.2.2 on 2023-06-21 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackathon_app', '0002_hackathon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hackathon',
            name='background_image',
            field=models.ImageField(upload_to='hackathon_app/images'),
        ),
        migrations.AlterField(
            model_name='hackathon',
            name='hackathon_image',
            field=models.ImageField(upload_to='hackathon_app/images'),
        ),
    ]
