# Generated by Django 4.2.2 on 2023-06-21 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackathon_app', '0003_alter_hackathon_background_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hackathon',
            name='background_image',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='hackathon',
            name='hackathon_image',
            field=models.URLField(),
        ),
    ]
