# Generated by Django 4.2.2 on 2023-06-21 16:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hackathon_app', '0004_alter_hackathon_background_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hackathon',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hackathon_app.registereduser'),
        ),
    ]
