# Generated by Django 4.2.2 on 2023-06-21 17:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hackathon_app', '0005_alter_hackathon_created_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnrolledHackathon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hackathon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hackathon_app.hackathon')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hackathon_app.registereduser')),
            ],
        ),
    ]
