# Generated by Django 4.2.2 on 2023-06-21 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hackathon_app', '0007_submission'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='submission',
            unique_together={('hackathon', 'user')},
        ),
    ]
